[theme]
base = "light"
primaryColor = "#1f6feb"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f8fa"
textColor = "#0a0a0a"

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = true
